source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'wdm', '>= 0.1.1' if Gem.win_platform?
gem 'isomorfeus-iodine', '~> 0.7.45'
gem 'roda', '~> 3.50.0'

gem 'opal', '~> 1.4.0.alpha1'
gem 'opal-zeitwerk', path: '../../opal-zeitwerk'
gem 'isomorfeus-asset-manager', path: '../../isomorfeus-asset-manager'
gem 'isomorfeus-redux', path: '../../isomorfeus-redux'
gem 'isomorfeus-policy', path: '../../isomorfeus-project/isomorfeus-policy' # '>= 2.0.0.rc5'
gem 'isomorfeus-transport',  path: '../../isomorfeus-project/isomorfeus-transport' # '>= 2.0.0.rc5'
gem 'isomorfeus-preact', path: '..'

group :test do
  gem 'rspec', '~> 3.10.0'
  gem 'isomorfeus-puppetmaster', path: '../../isomorfeus-puppetmaster'
end
