source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'iodine', '~> 0.7.44'
gem 'foreman', require: false

gem 'roda', '~> 3.46.0'

gem 'opal', github: 'janbiedermann/opal', branch: 'es6_modules_1_2'
gem 'isomorfeus-asset-manager', path: '../../isomorfeus-asset-manager'
gem 'isomorfeus-policy', path: '../../isomorfeus-project/isomorfeus-policy'
gem 'isomorfeus-transport', path: '../../isomorfeus-project/isomorfeus-transport'
gem 'isomorfeus-preact', path: '..'

group :test do
  gem 'rspec', '~> 3.8.0'
  gem 'isomorfeus-puppetmaster', '~> 0.4.1'
end
