source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'wdm', '>= 0.1.1' if Gem.win_platform?
gem 'concurrent-ruby-ext'
gem 'isomorfeus-iodine', '~> 0.7.47'
gem 'roda', '~> 3.53.0'

gem 'isomorfeus-preact', path: '..'

group :test do
  gem 'rspec', '~> 3.11.0'
  gem 'isomorfeus-puppetmaster', '~> 0.6.5'
end
