source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'wdm', '>= 0.1.1' if Gem.win_platform?
gem 'isomorfeus-iodine', '~> 0.7.45'
gem 'roda', '~> 3.50.0'

gem 'opal', '~> 1.3.2'
gem 'isomorfeus-policy', '>= 2.0.0.rc3'
gem 'isomorfeus-transport', '>= 2.0.0.rc3'
gem 'isomorfeus-preact', path: '..'

group :test do
  gem 'rspec', '~> 3.10.0'
  gem 'isomorfeus-puppetmaster', '~> 0.5.5'
end
