source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'iodine', '~> 0.7.44'
gem 'roda', '~> 3.47.0'

gem 'opal', github: 'janbiedermann/opal', branch: 'es6_modules_1_2'
gem 'isomorfeus-policy', path: '../../isomorfeus-project/isomorfeus-policy'
gem 'isomorfeus-transport', path: '../../isomorfeus-project/isomorfeus-transport'
gem 'isomorfeus-preact', path: '..'

group :test do
  gem 'rspec', '~> 3.8.0'
  gem 'isomorfeus-puppetmaster', '~> 0.5.2'
end
